### ISSUE TITLE
Add an arm64.whl for fastobo to pypi releases

### ISSUE THREAD

**Issue by cmungall** [fastobo/fastobo-py#313] opened 2022-10-21 19:06 UTC
Currently I am trying to combine ensmallen and fastobo in one package (oakx-grape) on an M1 Mac

Using ensmallen 0.8.28, which has an arm64.whl 
https://pypi.org/project/ensmallen/0.8.28/#files

I don't see an equivalent for fastobo

This results in:

```
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/pronto/xref.py", line 6, in <module>
    import fastobo
ImportError: dlopen(/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so, 0x0002): tried: '/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

AFAICT I can't use ensmallen in x86 mode (cc @justaddcoffee) so I seem to be stuck here

I've been told that building arm wheels automatically as part of CI is hard, but I found this, don't know how hard this would be to integrate:

https://github.com/pypa/cibuildwheel

**Comment by ravwojdyla** [comment] 2022-12-05 11:47
FYI this is a duplicate of https://github.com/fastobo/fastobo-py/issues/302

**Comment by althonos** [comment] 2022-12-06 21:12
Cool, thanks!

**Comment by kevinschaper** [comment] 2022-12-06 21:15
It's working for me too, thanks for the fix!

**Closed** 2022-12-06 21:47 UTC
Labels: distribution
